version: "3.7"

volumes:
  tuf-repository-service-api-data:
  tuf-repository-service-worker-data:
  tuf-repository-service-mq-data:
  tuf-repository-service-storage:
  tuf-repository-service-keystorage:
  tuf-repository-service-redis-data:


secrets:
  SECRETS_TRS_ADMIN_PASSWORD:
    external: True
  SECRETS_TRS_TOKEN_KEY:
    external: True
  # HTTPS (SSL)
  # API_KEY:
  #   external: True
  # API_CRT:
  #   external: True

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      - "tuf-repository-service-mq-data:/var/lib/rabbitmq"
    healthcheck:
      test: "exit 0"
    restart: always
    tty: true

  redis:
    image: redis:4.0
    volumes:
      - tuf-repository-service-redis-data:/data
    healthcheck:
      test: "exit 0"
    restart: always
    tty: true

  tuf-repository-service-worker:
    image: ghcr.io/kaprien/tuf-repository-service-worker:dev
    volumes:
      - tuf-repository-service-worker-data:/data
      - tuf-repository-service-storage:/var/opt/tuf-repository-service/storage
      - tuf-repository-service-keystorage:/var/opt/tuf-repository-service/keystorage
    environment:
      TRS_STORAGE_BACKEND: LocalStorage
      TRS_KEYVAULT_BACKEND: LocalKeyVault
      TRS_LOCAL_STORAGE_BACKEND_PATH: /var/opt/tuf-repository-service/storage
      TRS_LOCAL_KEYVAULT_PATH: /var/opt/tuf-repository-service/keystorage
      TRS_BROKER_SERVER: amqp://guest:guest@rabbitmq:5672
      TRS_REDIS_SERVER: redis://redis
      TRS_WORKER_ID: dev
    depends_on:
      - redis
      - rabbitmq
    healthcheck:
      test: "exit 0"
    restart: always
    tty: true

  web-server:
    image: python:3.10-slim-buster
    command: python -m http.server -d /www 8080
    volumes:
      - tuf-repository-service-storage:/www
    ports:
      - "8080:8080"

  tuf-repository-service-api:
    image: ghcr.io/kaprien/tuf-repository-service-api:dev
    volumes:
      - tuf-repository-service-api-data:/data
    ports:
      - 80:80
      - 443:443
    environment:
      TRS_BOOTSTRAP_NODE: "true"
      TRS_BROKER_SERVER: amqp://guest:guest@rabbitmq:5672
      TRS_REDIS_SERVER: redis://redis
      SECRETS_TRS_TOKEN_KEY: /run/secrets/SECRETS_TRS_TOKEN_KEY
      SECRETS_TRS_ADMIN_PASSWORD: /run/secrets/SECRETS_TRS_ADMIN_PASSWORD
      # HTTP (SSL)
      # SECRETS_TRS_SSL_CERT: /run/secrets/API_CRT
      # SECRETS_TRS_SSL_KEY: /run/secrets/API_KEY
    secrets:
      - SECRETS_TRS_ADMIN_PASSWORD
      - SECRETS_TRS_TOKEN_KEY
      # HTTPS (SSL)
      # - API_CRT
      # - API_KEY
    depends_on:
      - rabbitmq
      - redis
      - tuf-repository-service-worker
