name: Tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
    - uses: ammaraskar/sphinx-action@8b4f60114d7fd1faeba1a712269168508d4750d2
      with:
        docs-folder: "docs/"
        build-command: "make docs"
        pre-build-command: "apt-get update -y && apt-get install -y plantuml && pip install -r requirements-docs.txt"
